### ISSUE TITLE
where symfony routes are defined in this project?

### ISSUE THREAD

**Issue by mappedinn** [bayne/symfony-angular-todomvc#7]
I did not found where the routes are defined in the project...

How this is done?  _(if feel it is done throught the configuration of the `fos_rest`)_

What if someone would like to define the routes based on annotation? Is it recommended to avoid that for RESTful API???

If you have any link or any documentation related to definition of the routes in RESTful API without annotations or yml file, I will be happy.

Thanks,

**Comment by bayne** [comment]
Routes are generated based on the name of the controller method:

http://symfony.com/doc/master/bundles/FOSRestBundle/5-automatic-route-generation_single-restful-controller.html#define-resource-actions

If you want to manually define the routes:

http://symfony.com/doc/master/bundles/FOSRestBundle/7-manual-route-definition.html

As for best practice? I don't believe there is any efficiency trade-offs so it really boils down to the agreement between your project's collaborators/maintainers.

**Comment by mappedinn** [comment]
thanks @bayne
